### ISSUE TITLE
`Basics` documentation example incorrect: `sqrt >> isEven >> not`

### ISSUE THREAD

**Issue by lue-bird** [gren-lang/core#15]
https://github.com/elm/core/issues/1097

**Comment by alexislozano** [comment]
@lue-bird What do you think replacing 'sqrt' in the docs with `round`? `round` takes a `Float` and returns an `Int`. So it would make the example compilable:

```elm
round >> isEven >> not
```

**Comment by lue-bird** [comment]
Sounds good, maybe embedded in something like
```elm
[ 1.2, 3.7, -5.2, -10 ]
    |> Array.filter (round >> isEven >> not)
--> [ 1.2, -5.2 ]
```
(Btw, pinging me is fine but I have no more say or insight than you. I just happen to have been allowed to port `elm/` issues over)
