### ISSUE TITLE
number operations: only some truncate results to 32-bit

### ISSUE THREAD

**Issue by lue-bird** [gren-lang/core#17]
- `truncate` https://github.com/elm/core/issues/1079
- https://github.com/elm/core/issues/1003
- `Bitwise` https://github.com/elm/core/issues/870

The commonly suggested fix is to always truncate to 32-bit.

**Comment by robinheghan** [comment]
I think, unless Gren someday get's support for 64-bit ints, that the proper fix is to avoid truncating numbers to 32-bits except for bitwise operations.

**Comment by robinheghan** [comment]
This should be fixed in latest release. That is, only bitwise operations should truncate numbers to 32-bits now.
