### ISSUE TITLE
Core still imports Tuple

### ISSUE THREAD

**Issue by PixelPartner** [gren-lang/core#2]
If I recall correctly, one difference of gren from elm is to not use tuples, but records instead.

**Comment by robinheghan** [comment]
Where does this happen?

**Comment by PixelPartner** [comment]
LOL it's right in the README.md

**Comment by robinheghan** [comment]
Right, so this is a documentation issue, not an issue with the compiler or the source code?

**Comment by robinheghan** [comment]
Fixed in latest commit on main
