### ISSUE TITLE
`Array` documentation example incorrect: `indexedMap (,) [ 3, 3, 3 ] == [ ( 0, 3 ), ( 1, 3 ), ( 2, 3 ) ]` 

### ISSUE THREAD

**Issue by ossan-pg** [gren-lang/core#39]
There is a use of a non-existent function `(,)`, and tuples also appears.

https://github.com/gren-lang/core/blob/7e245da15940132137866b11da0528298702daff/src/Array.gren#L142

**Comment by robinheghan** [comment]
Fixed in upcomming release.
