### ISSUE TITLE
different `Bytes` lengths on `==` can still give `True`

### ISSUE THREAD

**Issue by lue-bird** [gren-lang/core#48]
In contrast to [json `Value`s](https://github.com/gren-lang/core/issues/42), the documentation don't explicitly discourage calling `==` on `Bytes`, neither in

- https://discourse.elm-lang.org/t/function-equality/7538/24
- https://package.elm-lang.org/packages/elm/core/latest/Basics#equality

https://github.com/elm/bytes/issues/15
The reason for this could again be, that, like for json values, the equal-check function only compares properties of the first argument. Here's one fix https://github.com/elm/core/pull/1092/files

**Comment by blaix** [comment]
@robinheghan any objection to the fix linked in the description? This is affecting some cli work I'm doing so I'd be happy to test the fix and submit a PR if you think it looks good.

**Comment by robinheghan** [comment]
No objection to the fix.
