### ISSUE TITLE
`Regex.fromString ""` → js heap out of memory error

### ISSUE THREAD

**Issue by lue-bird** [gren-lang/core#54]
https://github.com/elm/regex/issues/6

**Comment by perkee** [comment]
Note that an empty string is not the only way to have a match with zero width. If you split on word boundaries `\b` you'll also have zero width matches. See example https://github.com/elm/regex/issues/6#issuecomment-2273782545

**Comment by robinheghan** [comment]
@perkee Thank you for letting me know. I believe I've fixed this by using `string.split(regex, limit)` instead of the custom implementation. Should be included in the next release.

**Comment by robinheghan** [comment]
For reference: [Fix Regex.splitAtMost](https://github.com/gren-lang/core/commit/50a5a0bf12ae20635defafe66933fae1e1ec727a)
