### ISSUE TITLE
prefix binary operations → curry-able functions

### ISSUE THREAD

**Issue by lue-bird** [gren-lang/core#6]
Using an operator's prefix notation is unintuitive and prone to errors:
```elm
Just 3 |> Maybe.map ((-) 3)
--> Just 0
```
Proposal: remove `(symbol)` syntax and prefix binary operations in favor of actual functions:
- `(^) n exp` → `n |> toPower exp`
- `(/) n div` → `n |> divideBy div`
- `(//) n div` → `n |> Int.divideBy div`
- `(*) n mul` → `n |> multiplyBy mul`
- `(-) n sub` → `n |> subtract sub`
- `(+) a b` → `b |> add a`
- ...
- `bool |> and also`
- `bool |> or also`
- `min a b` → `a |> atMost b`
- `max a b` → `a |> atLeast b`
- `(<) a b` → `a |> isBelow b`
- `(<=) a b` → `a |> isAtMost b`
- `(>=) a b` → `a |> isAtLeast b`
- `(>) a b` → `a |> isAbove b`
- `(++) init tail`, `.append init tail` → `init |> .append tail`
- `(::) element list` → `list |> cons element`
- `(<|)` → `apply`? remove?
- `(|>)` → `eat`/`feed`/`feedWith`/`with`? remove?
- `(>>)` → remove?
- `(<<)` → `over`/`overTo`/`to`/`then`/`thenTo`/`compose`/`furthermore`/`furtherTo`? remove?

including parser operators (replaced by `|> skip`, `|> grab`, ...).

My secret hope is that just like `%`, which was removed in favor of `modBy` & `remainderBy`,
conventions will develop abandoning, for example

- `&&`, `||`, `min`, `max`, unary `-`, `^`, all parser operators
- `init |> append middle |> append tail`
  \> `[ init, middle |> operation, tail ] |> concat`
  \> `init ++ (middle |> operation) ++ tail`

(I'm not opposed to removing all listed and more)

**Comment by robinheghan** [comment]
I agree 👍 

Since this includes removing support in the language/compiler, would you mind moving this issue to the compiler repo?

**Comment by avh4** [comment]
imo, maybe `(<|)`, `(|>)`, `(>>)`, and `(<<)` don't need replacements since you could just write an anonymous lambda for them instead.

**Comment by lue-bird** [comment]
Moved to https://github.com/gren-lang/compiler/issues/79
