### ISSUE TITLE
Crypto: support `Ed25519` key pairs

### ISSUE THREAD

**Issue by eberfreitas** [gren-lang/core#91]
Hello folks!

I'm trying to port Paseto's javascript library into Gren but it seems like, when generating keys, they use `Ed25519` and I couldn't find a way to generate those with gren's crypto implementation.

I would gladly try to help if this is actually absent. Maybe I'm overlooking something or don't really understand how those keys function.

Thank you!

**Comment by robinheghan** [comment]
I believe Ed25519 are not yet supported by the WebCrypto API, but that it will be added at some point in the future (NodeJS v22 has experimental support). Once this becomes more available, it will be natural to support in Gren as well.

**Comment by eberfreitas** [comment]
Ah, that makes sense @robinheghan! Is there a threshold we should wait for until adopting this? Can I use... reports 14.7% of global usage.

**Comment by robinheghan** [comment]
It should work on all browsers and the current LTS version of NodeJS. So it will be a while.

**Comment by eberfreitas** [comment]
Closing this for now. Thank you!
